stages:
  - build
  - deploy
  - push

build-dev:
  stage: build
  only:
    - dev-lacoste-mini-program-unionid
  tags:
    - shell-dev
  script:
    - mvn -Dmaven.test.skip=true clean package

deploy-dev:
  stage: deploy
  only:
    - dev-lacoste-mini-program-unionid
  tags:
    - shell-dev
  script:
    - cd /root/docker-swarm/
    - docker stack deploy -c wechat.yml wechat

push-dev:
  stage: push
  only:
    - dev-lacoste-mini-program-unionid
  tags:
    - shell-dev
  script:
    - mvn docker:push

build-uat:
  stage: build
  only:
    - uat
  tags:
    - shell-uat
  script:
    - mvn -Dmaven.test.skip=true clean package

deploy-uat:
  stage: deploy
  only:
    - uat
  tags:
    - shell-uat
  script:
    - cd /root/docker-swarm/
    - docker stack deploy -c wechat.yml wechat

push-uat:
  stage: push
  only:
    - uat
  tags:
    - shell-uat
  script:
    - mvn docker:push