stages:
  - build
  - deploy
  - push

build-dev:
  stage: build
  only:
    - dev
  tags:
    - shell-60
  script:
    - mvn -Dmaven.test.skip=true clean package
    
push-dev:
  stage: push
  only:
    - dev
  tags:
    - shell-60
  script:
    - mvn docker:push

deploy-dev:
  stage: deploy
  only:
    - dev
  tags:
    - shell-53
  script:
    - cd /etc/docker-swarm/
    - docker stack deploy -c wechat.yml wechat
