stages:
  - build
  - push
  - deploy

build-dev:
  stage: build
  only:
    - dev
  tags:
    - shell-dev-build
  script:
    - mvn -Dmaven.test.skip=true clean package
    
push-dev:
  stage: push
  only:
    - dev
  tags:
    - shell-dev-build
  script:
    - mvn docker:push

deploy-dev:
  stage: deploy
  only:
    - dev
  tags:
    - shell-dev-deploy
  script:
    - cd /root/docker-swarm/
    - docker stack deploy -c wechat1.yml wechat1
    
deploy-uat:
  stage: deploy
  only:
    - uat
  tags:
    - shell-qa-deploy
  script:
    - cd /root/docker-swarm/
    - docker stack deploy -c wechat1.yml wechat1
