stages:
  - build
  - deploy
  - push

build-dev:
  stage: build
  only:
    - dev
  tags:
    - shell-dev
  script:
    - mvn -Dmaven.test.skip=true clean package

deploy-dev:
  stage: deploy
  only:
    - dev
  tags:
    - shell-dev
  script:
    - cd /etc/docker-swarm/
    - docker stack deploy -c wechat.yml wechat

push-dev:
  stage: push
  only:
    - dev
  tags:
    - shell-dev
  script:
    - mvn docker:push