stages:
- build
- push
- deploy

#开发环境打包发布
build-dev:
  stage: build
  only:
  - dev
  tags:
  - shell-build-dev
  script:
  - mvn -Dmaven.test.skip=true clean package

push-dev:
  stage: push
  only:
  - dev
  tags:
  - shell-build-dev
  script:
  - mvn docker:push

deploy-dev:
  stage: deploy
  only:
  - dev
  tags:
  - shell-deploy-dev
  script:
  - cd /root/docker-swarm/
  - docker stack deploy -c wechat1.yml wechat1